# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 21:19
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assoc', models.CharField(max_length=100)),
                ('contest', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('stream', models.CharField(blank=True, choices=[('I', 'International'), ('N', 'National'), ('Y', 'Youth'), ('S', 'Senior')], max_length=1, null=True, verbose_name='Stream')),
                ('type', models.CharField(choices=[('q', 'Quartet'), ('c', 'Chorus')], max_length=1)),
                ('year', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('assoc', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('c', 'Chorus'), ('q', 'Quartet')], max_length=1)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
                ('alias_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scores.Contestant')),
            ],
        ),
        migrations.CreateModel(
            name='ContestantApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
                ('rank_m', models.IntegerField(blank=True, null=True, verbose_name='Music Rank')),
                ('rank_p', models.IntegerField(blank=True, null=True, verbose_name='Performance Rank')),
                ('rank_s', models.IntegerField(blank=True, null=True, verbose_name='Singing Rank')),
                ('m', models.IntegerField(verbose_name='Music')),
                ('p', models.IntegerField(verbose_name='Performance')),
                ('s', models.IntegerField(verbose_name='Singing')),
                ('tot_score', models.IntegerField(verbose_name='Total')),
                ('m_pc', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Music %')),
                ('p_pc', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Presentation %')),
                ('s_pc', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Singing %')),
                ('pc_score', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Total %')),
                ('n', models.IntegerField(verbose_name='Number of songs')),
                ('size', models.IntegerField(blank=True, null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.Contest')),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.Contestant')),
            ],
        ),
        migrations.CreateModel(
            name='ContestURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cat', models.CharField(choices=[('m', 'Music'), ('s', 'Singing'), ('p', 'Presentation'), ('a', 'Administration')], max_length=1, verbose_name='Category')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('part', models.CharField(choices=[('tenor', 'T'), ('lead', 'L'), ('bari', 'Br'), ('bass', 'Bs'), ('director', 'Dir')], max_length=5, verbose_name='Category')),
                ('contestantapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.ContestantApp')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
                ('alias_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scores.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
                ('alias_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scores.Song')),
            ],
        ),
        migrations.CreateModel(
            name='SongApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('m', models.IntegerField(verbose_name='Music')),
                ('mr', models.IntegerField(blank=True, null=True, verbose_name='Music Penalty')),
                ('p', models.IntegerField(verbose_name='Performance')),
                ('pr', models.IntegerField(blank=True, null=True, verbose_name='Performance Penalty')),
                ('s', models.IntegerField(verbose_name='Singing')),
                ('tot_score', models.IntegerField(verbose_name='Total')),
                ('m_pc', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Music %')),
                ('p_pc', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Presentation %')),
                ('s_pc', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Singing %')),
                ('pc_score', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Total %')),
                ('n', models.IntegerField(verbose_name='Number of songs')),
                ('contestantapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.ContestantApp')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.Song')),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(choices=[('I', 'International'), ('N', 'National'), ('Y', 'Youth'), ('S', 'Senior')], max_length=1, verbose_name='Stream')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('contestantapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.ContestantApp')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('songapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.SongApp')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.Person'),
        ),
        migrations.AddField(
            model_name='judge',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.Person'),
        ),
    ]
